spring.application.name=bookManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/bookmanagement
spring.datasource.username=postgres
spring.datasource.password=postgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.show-sql=true
